apiVersion: v1
kind: Namespace
metadata:
  name: ticketing-platform
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: ticketing-platform
data:
  REDIS_URL: "redis://redis:6379"
